# Generated by Django 4.2.23 on 2025-09-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('billing_cycle', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], max_length=10, null=True)),
                ('stripe_price_id', models.CharField(blank=True, help_text='Leave blank for Free plans', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_gallery', models.BooleanField(default=False)),
                ('allow_music', models.BooleanField(default=False)),
                ('allow_custom_banner', models.BooleanField(default=False)),
            ],
        ),
    ]
