# Generated by Django 4.2.23 on 2025-11-29 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='crop_height',
            field=models.FloatField(default=100.0, help_text='Crop height in percentage'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='crop_width',
            field=models.FloatField(default=100.0, help_text='Crop width in percentage'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='crop_x',
            field=models.FloatField(default=0.0, help_text='Crop X position'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='crop_y',
            field=models.FloatField(default=0.0, help_text='Crop Y position'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='position_x',
            field=models.FloatField(default=50.0, help_text='Horizontal position in percentage'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='position_y',
            field=models.FloatField(default=50.0, help_text='Vertical position in percentage'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='rotation',
            field=models.FloatField(default=0.0, help_text='Rotation in degrees'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='zoom',
            field=models.FloatField(default=1.0, help_text='Zoom level (1.0 = 100%)'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='memorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='memorial.memorial'),
        ),
    ]
