# Generated by Django 4.2.23 on 2025-11-29 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0002_alter_galleryimage_options_galleryimage_crop_height_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='crop_height',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='crop_width',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='crop_x',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='crop_y',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='position_x',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='position_y',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='rotation',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='zoom',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='memorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='memorial.memorial'),
        ),
    ]
