# Generated by Django 4.2.23 on 2025-12-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorial', '0004_tribute_status_tribute_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='story',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
